from pathlib import Path
import json,hashlib,re,collections,datetime
base=Path('docs/production-chain-forensics-20260928');ev=base/'evidence';arc=base/'prompts';arc.mkdir(exist_ok=True);raw=ev/'generation-calls';raw.mkdir(exist_ok=True)
imgs=[json.loads(x) for x in (ev/'image-events.jsonl').read_text(encoding='utf-8').splitlines()];calls=[json.loads(x) for x in (ev/'tool-calls.jsonl').read_text(encoding='utf-8').splitlines()]
gen=[r for r in calls if 'tools.image_gen__imagegen(' in r['input']]
for r in gen:(raw/(r['thread_id'][:8]+'-'+str(r['ordinal'])+'.js')).write_text(r['input'],encoding='utf-8')
# Compare exact generated bytes to project copies; never alter an image.
by_size=collections.defaultdict(list)
for root in ['artifacts','docs','web/art']:
 for p in Path(root).rglob('*.png'):
  if 'production-chain-forensics-20260928' not in p.parts:by_size[p.stat().st_size].append(p)
hashes={};rows=[]
for i,r in enumerate(imgs,1):
 pid=f'IG{i:03d}';r['archive_id']=pid;source=Path(r.get('savedPath',''));r['source_exists']=source.is_file();r['exact_project_copies']=[]
 if source.is_file():
  digest=hashlib.sha256(source.read_bytes()).hexdigest();r['sha256']=digest
  for p in by_size[source.stat().st_size]:
   key=str(p)
   if key not in hashes:hashes[key]=hashlib.sha256(p.read_bytes()).hexdigest()
   if hashes[key]==digest:r['exact_project_copies'].append(p.as_posix())
 gc=[g for g in gen if g['thread_id']==r['thread_id'] and g['ordinal']<r['ordinal']];g=max(gc,key=lambda x:x['ordinal']) if gc else None
 r['level']='ORIGINAL' if g else 'PARTIAL';r['field_origin']='thread_items.item_json.revisedPrompt (verbatim tool-event field; not silently relabelled as submitted prompt)'
 r['generation_call']=({k:g[k] for k in ['source','line','ordinal','call_id']} if g else None)
 # Static linkage: include source definitions for load(...) variables, without running historical code.
 contexts=[];done=set()
 def defs(inp,before):
  for key in re.findall(r'load\([\"\']([^\"\']+)[\"\']\)',inp):
   if key in done:continue
   done.add(key);pat=re.compile(r'store\(\s*[\"\']'+re.escape(key)+r'[\"\']\s*,')
   cs=[c for c in calls if c['thread_id']==r['thread_id'] and c['ordinal']<before and pat.search(c['input'])]
   if cs:
    c=max(cs,key=lambda x:x['ordinal']);fn=c['thread_id'][:8]+'-'+str(c['ordinal'])+'.js';(raw/fn).write_text(c['input'],encoding='utf-8');contexts.append(fn);defs(c['input'],c['ordinal'])
 if g:defs(g['input'],g['ordinal'])
 r['definition_files']=list(dict.fromkeys(contexts))
 # Distinguish directed image edit from reference-guided creation by instruction; API endpoint is not exposed.
 prompt=r.get('revisedPrompt','');r['intent']='image edit / style transfer' if re.search(r'(?i)(precise.object.edit|LOCAL EDIT|STYLE TRANSFER EDIT|EDIT THIS|Edit the attached|Edit this|Revise this|EDIT TARGET|background-extraction edit)',prompt) else 'reference-guided generation'
 r['reference_recovery']='See original call and load/store definitions; role and array kept verbatim. No invented reference list.'
 md=[f'# {pid} · {r["level"]}',f'- 时间：{r["time"]}\n- 会话：`{r["thread_id"]}`；item：`{r["item_id"]}`；ordinal：{r["ordinal"]}\n- 状态：{r.get("status")}；意图：{r["intent"]}\n- 透明参数：{r.get("transparentBackground")}\n- 输出：`{r.get("savedPath")}`\n- SHA256：`{r.get("sha256","MISSING")}`\n- 项目内逐字节一致副本：'+('、'.join('`'+x+'`' for x in r['exact_project_copies']) or '未找到；可能经过裁切、缩放、分割，不能凭视觉声称字节一致。')]
 if g:md.append(f'## 原始调用与输入参考\n\n[真实调用](../evidence/generation-calls/{g["thread_id"][:8]}-{g["ordinal"]}.js)。原始 JSONL `{g["source"]}` 第 {g["line"]} 行。按同会话 ordinal 对应最近生成调用；同批并发调用内用下方完整提示词辨别对象。')
 if contexts:md.append('变量定义（真实原文，未执行）：\n\n'+'\n'.join(f'- [{x}](../evidence/generation-calls/{x})' for x in dict.fromkeys(contexts)))
 md.append('## 工具事件记录的完整 Prompt\n\n以下为 SQLite `revisedPrompt` 字段原文。提交端 prompt 的字面量/拼接表达式见原始调用；二者不能未经核对就视为完全相同。不是根据成图补写的 Prompt。\n\n```text\n'+prompt+'\n```')
 (arc/(pid+'.md')).write_text('\n\n'.join(md),encoding='utf-8');rows.append(r)
(ev/'image-archive-index.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8')
idx=['# ImageGen Prompt Archive','恢复了 80 个已完成 imageGeneration 事件，逐条保存真实工具字段、原始调用、输入变量定义及输出哈希。80 不是计费调用次数；失败、重试、未投影事件不以此计数。IG012 是同一早期会话的应用图标，保留作边界证据，不纳入 Kitchen 因果统计。','**分级：** ORIGINAL＝真实工具记录/调用；PARTIAL＝只有部分真实指令；RECONSTRUCTED＝分析者重建意图。本档案不编造缺失 Prompt。无图像生成的原型标 N/A，不凑 RECONSTRUCTED Prompt。','**模式：** 带 reference 的生成不能自动当作“编辑上一张”。本档案区分参考引导生成与明确 image edit/style transfer 意图；内置工具未暴露 images API endpoint，不推断实际服务端模式或模型版本。','|ID|时间（+08）|会话 / ordinal|分级|意图|真实提示词开头|','|---|---|---|---|---|---|']
for r in rows:idx.append(f'|[{r["archive_id"]}](prompts/{r["archive_id"]}.md)|{r["time"][:19]}|{r["thread_id"][:8]} / {r["ordinal"]}|{r["level"]}|{r["intent"]}|{r.get("revisedPrompt","")[:90].replace(chr(10)," ").replace("|","/")}|')
(base/'04-imagegen-prompt-archive.md').write_text('\n\n'.join(idx[:4])+'\n\n'+'\n'.join(idx[4:])+'\n',encoding='utf-8')
print('prompt archive',len(rows),collections.Counter(r['level'] for r in rows),'source images',sum(r['source_exists'] for r in rows),'exact copy matches',sum(bool(r['exact_project_copies']) for r in rows),'generation calls',len(gen))
