from pathlib import Path
p=Path('web/exploration.js');s=p.read_text(encoding='utf-8').replace('discoveryCount,randomUnit','discoveryCount,randomUnit,checkedIncome')
s=s.replace('members=[],now=Date.now())','members=[],now=Date.now(),{light=false}={})')
s=s.replace("const materialChance=Math.min(.6,.05+.025*G+.04*A+.02*rank(s,'TRIP-A')+(rank(s,'TRIP-S')?.06:0));", "light=!!(light&&route.id!=='yard'&&rank(s,'TRIP-5'));\n  const baseUnits=route.baseUnits-(light?1:0),hours=route.hours*(light?.8:1);\n  const materialChance=Math.min(.6,.05+.025*G+.04*A+(rank(s,'TRIP-3')?.03*A:0)+(rank(s,'TRIP-S')?.06:0));")
s=s.replace("+.03*rank(s,'TRIP-C')", "+(rank(s,'TRIP-3')?.02*A:0)")
s=s.replace('return {route,unlocked,team,G,F,A,materialChance,clueChance,clues,directedUnits:Math.min(route.baseUnits,', 'return {route,unlocked,team,G,F,A,materialChance,clueChance:clues.length?clueChance:0,clues,light,baseUnits,hours,cpReward:rank(s,\'TRIP-1\')?baseUnits*6:0,directedUnits:Math.min(baseUnits,')
s=s.replace("rank(s,'TRIP-B')", "rank(s,'TRIP-2')").replace("rank(s,'TRIP-D')", "rank(s,'TRIP-4')")
s=s.replace('minUnits:route.baseUnits,maxUnits:route.baseUnits+1', 'minUnits:baseUnits,maxUnits:baseUnits+1')
s=s.replace('directed=[],priority=null}', 'directed=[],priority=null,light=false}')
s=s.replace('explorationInfo(s,routeId,members,now)', 'explorationInfo(s,routeId,members,now,{light})')
s=s.replace('info.route.baseUnits+(bonus?1:0)', 'info.baseUnits+(bonus?1:0)').replace('info.route.hours*3600000', 'info.hours*3600000')
s=s.replace("remaining,clueOrder:order", "remaining,cpReward:info.cpReward&&randomUnit(random)<.2?info.cpReward:0,cpProcessed:false,clueOrder:order")
s=s.replace('snapshot:{G:info.G', 'snapshot:{light:info.light,baseUnits:info.baseUnits,G:info.G')
s=s.replace("t.status='recalled';t.remaining=[];", "t.status='recalled';t.remaining=[];t.cpReward=0;t.cpProcessed=true;")
s=s.replace('let clue=null;', 'let clue=null,cp=0;\n  if(!t.cpProcessed){cp=t.cpReward??0;checkedIncome(s,cp);s.cp+=cp;t.cpProcessed=true;}')
s=s.replace('return {materials:received,clue,', 'return {materials:received,cp,clue,')
p.write_text(s,encoding='utf-8')
p=Path('web/knowledge.js');s=p.read_text(encoding='utf-8').replace("const levels=[false,rank(s,'OBS-A')>=1,rank(s,'OBS-A')>=2,rank(s,'OBS-A')>=3,rank(s,'OBS-C')>=1,rank(s,'OBS-C')>=2];", "const levels=[false,!!rank(s,'OBS-1'),!!rank(s,'OBS-1'),!!rank(s,'OBS-3'),!!rank(s,'OBS-3'),!!rank(s,'OBS-3')];")
s=s.replace("rank(s,'OBS-D')", "rank(s,'OBS-4')").replace("throw Error('CP不足')", "throw Error('CP还差'+(info.studyCost-s.cp)+'。可以先出售伙伴，或继续寻访免费线索。')")
p.write_text(s,encoding='utf-8')
p=Path('web/candidate-query.js');s=p.read_text(encoding='utf-8').replace("rank(s,'OBS-B')","rank(s,'OBS-2')").replace('先判定是否入池','先判断本批能否出现');p.write_text(s,encoding='utf-8')
p=Path('web/recipe-book.js');s=p.read_text(encoding='utf-8').replace("import {speciesKey", "import {cookingTiming,batchSignature} from './progression.js';\nimport {speciesKey")
s=s.replace('符合条件会加入对应结果池，同一批可能出现其他品种，不能保证每批获得。','这批可能出现这些伙伴，数量不固定；符合条件也不保证每批获得。')
s=s.replace('minutes:tool?.[`lv_${level}_min`]', 'originalMinutes:tool?.[`lv_${level}_min`],minutes:tool?cookingTiming(s,tool[`lv_${level}_min`],{signature:batchSignature(r.egg,r.toolId,r.ingredients),now}).minutes:undefined')
p.write_text(s,encoding='utf-8')
