from pathlib import Path
p=Path('web/progress-save.js');s=p.read_text(encoding='utf-8').replace('SKILL_BY_ID,TRADE_CATEGORIES','SKILL_BY_ID,SKILLS,TRADE_CATEGORIES')
s=s.replace("int(p.skillVersion,'手艺版本',2,2);", "const replay={...s,progress:{...p,skills:{}}};for(const def of SKILLS)if(p.skills[def.id]){if(skillGate(replay,def.id))fail('手艺学习顺序 '+def.id);replay.progress.skills[def.id]=1;}\n  int(p.skillVersion,'手艺版本',2,2);")
s=s.replace("if(p.hotStove!==null){", "if(p.replicate!==undefined&&p.replicate!==null&&(typeof p.replicate!=='string'||!ABILITIES[p.replicate]))fail('复刻目标');\n  if(p.hotStove!==null){")
s=s.replace("if(b.returnTicket!==null)int(b.returnTicket,'返料票据',0,74);", "if(b.returnTicket!==null){int(b.returnTicket,'返料票据',0,74);if(!b.returnEligible||[68,69,70].includes(b.returnTicket)||!s.batch.ingredients.includes(b.returnTicket))fail('返料票据来源');}")
p.write_text(s,encoding='utf-8')
p=Path('web/workshop-ui.js');s=p.read_text(encoding='utf-8').replace('function initDraft(){if(draft)return;', 'function initDraft(){if(draft&&(draftReset||draftSteps.length))return;')
s=s.replace('<h3>${info.known?escape(info.name):\'尚未收录\'}</h3>', '<h3>${info.known?escape(info.name):\'尚未收录\'}</h3><p>${info.full?\'获取方法已知 · 实际收取后收入图鉴\':info.silhouette?\'已知：部分线索 · 待了解：完整获取方法\':\'待了解：蛋种、厨具、材料与出现条件\'}</p>')
s=s.replace('<button class="orange" data-study="${key}">研读获取方法 · ${info.studyCost} CP</button>', '<button class="orange" data-study="${key}">研读获取方法 · ${info.studyCost} CP</button>${s.cp<info.studyCost?`<p class="shortage">CP还差${info.studyCost-s.cp}。可以先出售伙伴，或继续寻访免费线索。</p>`:\'\'}')
p.write_text(s,encoding='utf-8')
p=Path('web/knowledge.js');s=p.read_text(encoding='utf-8').replace(".map(c=>c.label));", ".map(c=>(c.met?'已满足：':'尚缺：')+c.label));");p.write_text(s,encoding='utf-8')
p=Path('web/candidate-query.js');s=p.read_text(encoding='utf-8').replace("import {speciesCode}","import {speciesCode,ingredientName}")
s=s.replace("action:missing&&extra?'换一味':missing?'添一味':'少一味'", "action:missing&&extra?'将'+ingredients.filter(id=>!r.ingredients.includes(id)).map(ingredientName).join('、')+'换为'+r.ingredients.filter(id=>!ingredients.includes(id)).map(ingredientName).join('、'):missing?'添一味：'+r.ingredients.filter(id=>!ingredients.includes(id)).map(ingredientName).join('、'):'少一味：'+ingredients.filter(id=>!r.ingredients.includes(id)).map(ingredientName).join('、')")
p.write_text(s,encoding='utf-8')
