import {characterImage} from '../../catalog.js';
import {VISITORS,VISITOR_DIALOGUES,helpForStep} from './copy.js';
const A='/web/art/',npc='./assets/regular-old-customer-v1.png';
const names=['常客来访','第一次寻访','带回素材与线索','新伙伴建议','发现与新组合','摆货与收益','常客回访','下一锅'];
let step=0,tab='推荐',help=false,stock=[6,6],dialogueTurn=0;
const img=(src,cls='',alt='')=>`<img src="${src}" class="${cls}" alt="${alt}" draggable="false">`;
const next=(label='继续')=>`<button class="primary" data-next>${label}</button>`;
const actions=label=>`<div class="actions footer-action">${next(label)}</div>`;
const tabs=()=>`<nav class="tabs" aria-label="下一锅方向">${['推荐','新伙伴','订单','多赚'].map(t=>`<button class="${tab===t?'active':''}" data-tab="${t}" aria-pressed="${tab===t}">${t}</button>`).join('')}</nav>`;
function dialogue(layout,repeat=false){
 const visitor=VISITORS.RG1,turns=VISITOR_DIALOGUES.RG1[repeat?'repeat':'first'],current=turns[Math.min(dialogueTurn,turns.length-1)],last=dialogueTurn>=turns.length-1,speech=current.text;
 const reply=dialogueTurn?`<p class="player-reply">你：${turns[dialogueTurn-1].reply}</p>`:'';
 const buttons=`<div class="actions"><button class="defer" data-defer>稍后再来</button>${last?next(current.reply):`<button class="primary" data-talk>${current.reply}</button>`}</div>`;
 return layout==='a'?`<div class="scene-conversation">${img('./assets/'+visitor.scene,'scene-full',visitor.name+'在'+visitor.place)}<span class="place-tag">${visitor.place}</span><section class="dialogue scene-dialogue"><span class="speaker">${visitor.name}</span>${reply}<p class="speech">${speech}</p>${last?`<p class="dialogue-cue">${repeat?visitor.request:visitor.cue}</p>`:''}${buttons}</section></div>`:
 `<section class="note-sheet"><div class="visitor">${img(npc,'npc','提菜篮的老街坊')}<div><b>${visitor.name}</b><small>${repeat?'又来买早饭了':'刚买过早饭'}</small></div></div><span class="kicker">${repeat?'回访':'来访'}</span>${reply}<p class="speech">${speech}</p>${last?`<p class="tip">${repeat?visitor.request:visitor.cue}</p>`:''}${buttons}</section>`;
}
function partner(){return `<article class="target"><div class="target-top"><span class="mystery">?</span><div><b>C129 · 可以试做</b><small>平底锅 · 荠菜<br>已知线索都能用上</small></div></div><div class="set">${img(A+'golden-kitchen/tool-1.png')}<span>＋</span>${img(A+'golden-journey/material-75.png')}<span>荠菜</span></div><div class="actions">${next('准备这一锅')}</div></article>`;}
function content(layout){
 if(step===0||step===6)return dialogue(layout,step===6);
 if(step===1)return `<div class="paper-content"><span class="kicker">第一次出门</span><h3>谷地早市</h3>${img(A+'golden-journey/node-V.png','region-art')}<p class="region-copy">菜畦边、谷物棚，早上最热闹。</p><div class="unknown-slots"><div class="unknown-slot"><b>?</b><small>未发现素材</small></div><div class="unknown-slot"><b>?</b><small>未发现素材</small></div></div><p class="screen-note">这里还有没听过的做法</p><div class="status-line"><span>同行</span><b>鸡宝 · 已选好</b></div><p class="tip">伙伴出门后，厨房和生意照常进行。</p>${actions('出发')}</div>`;
 if(step===2)return `<div class="paper-content"><span class="kicker">寻访回来了</span><h3>寻访收获</h3><div class="material">${img(A+'golden-journey/material-75.png')}<div><b>荠菜 ×2</b><small>蔬菜 · 商店可以补货了</small></div></div><section class="clue"><b>新线索</b><p>荠菜切碎，拌进饼里，用平底锅煎熟。</p></section><p class="tip">荠菜已可补货，这条线索也记进了线索册。</p>${actions('收下 · 去厨房')}</div>`;
 if(step===3)return `${tabs()}<div class="paper-content"><span class="kicker">新伙伴 · 最近的目标</span>${partner()}<p class="tip">先看线索最接近完整的伙伴。点击准备后，还能检查厨具、调味和费用。</p></div>`;
 if(step===4)return `<div class="paper-content"><span class="kicker">发现荠菜煎饼鸡</span><h3>新组合可上架</h3><div class="bird-row"><div class="bird">${img(characterImage(0,128),'','荠菜煎饼鸡')}<b>荠菜煎饼鸡</b><small>这锅收获 7 只</small></div><span class="plus">＋</span><div class="bird">${img(characterImage(0,3),'','香煎鸡')}<b>香煎鸡</b><small>可摆 8 只</small></div></div><div class="gain"><span>家常小铺 · 完整组合</span><b>额外 +25%</b><p>两种各摆 6 只，可获得组合加价</p></div><p class="tip">两种伙伴都够用，可以直接摆成组合。</p>${actions('去摆货')}</div>`;
 if(step===5)return `<div class="paper-content"><span class="kicker">家常小铺</span><h3>摆货</h3>${['荠菜煎饼鸡','香煎鸡'].map((name,i)=>`<label class="stock-row">${img(characterImage(0,i?3:128))}<span><b>${name}</b><small>可摆 ${i?8:6} 只</small></span><input type="number" data-stock="${i}" aria-label="${name}摆货数量" min="0" max="${i?8:6}" value="${stock[i]}"></label>`).join('')}<div class="gain"><span>本次组合</span><b>${stock.every(n=>n>=6)?'已凑齐 · +25%':'尚未凑齐'}</b><p>${stock.every(n=>n>=6)?'符合菜单的出品享受加价':'两种各摆 6 只，可获得组合加价'}</p></div><p class="tip">每种留 1 只在家，其余都可摆上摊。</p>${actions('确认开摊')}</div>`;
 if(step===7){const cards=tab==='新伙伴'?`<article class="target"><div class="target-top"><span class="mystery">?</span><div><b>C131 · 还缺厨具</b><small>荠菜 · 谷豆与面食<br>需要竹蒸笼</small></div></div><div class="actions"><button class="secondary" data-detail>看线索</button></div></article>`:tab==='订单'?`<article class="target"><b>老顾客加订</b><small>荠菜煎饼鸡还差 2 只</small><div class="actions"><button class="primary" data-detail>准备补货</button></div></article>`:tab==='多赚'?`<article class="target"><b>按厨具查看收益</b><small>每种厨具列出当前收益最高的配方<br>显示每小时净收益、耗时和成本</small><div class="actions"><button class="secondary" data-detail>查看收益说明</button></div></article>`:`<article class="target"><b>给老顾客补两份</b><small>荠菜煎饼鸡还差 2 只<br>多出的可留着摆摊</small><div class="set">${img(A+'golden-kitchen/tool-1.png')}<span>＋</span>${img(A+'golden-journey/material-75.png')}</div><div class="actions"><button class="primary" data-detail>准备这一锅</button></div></article><article class="target"><b>想认识新伙伴？</b><small>新伙伴页按线索册列出最近的目标。</small><div class="actions"><button class="secondary" data-tab="新伙伴">看新伙伴</button></div></article>`;return `${tabs()}<div class="paper-content">${cards}<p class="tip">先准备厨具和调味，确认后再开火。</p><button class="secondary" data-restart>再体验一次</button></div>`;}
}
const helpMarkup=()=>{const copy=helpForStep(step);return `<div class="dialog-overlay"><section class="help-card" role="dialog" aria-modal="true" aria-label="${copy.title}"><h3>${copy.title}</h3>${copy.sections.map(([title,body])=>`<h4>${title}</h4><p>${body}</p>`).join('')}<button class="primary" data-help-close>知道了</button></section></div>`;};
function render(){
 for(const layout of ['a','b']){const root=document.querySelector('#layout-'+layout);root.innerHTML=`<header class="game-head"><span class="wallet">${img(A+'golden-business/coin.png')} 1,280</span><b>${step===1||step===2?'寻访':step===3||step===7?'下一锅':'生意'}</b><button class="round" data-help aria-label="查看帮助">?</button></header><div class="game-body">${content(layout)}</div><nav class="game-nav" aria-label="主页面"><span>厨房</span><span>农场</span><span class="${step===0||step>=4&&step<=6?'on':''}">生意</span><span class="${step===1||step===2?'on':''}">寻访</span><span>图鉴</span></nav>${help?helpMarkup():''}`;
 root.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{dialogueTurn=0;step=Math.min(7,step+1);if(step===3)tab='新伙伴';if(step===7)tab='推荐';render();});
 root.querySelectorAll('[data-talk]').forEach(b=>b.onclick=()=>{dialogueTurn++;render();root.querySelector('[data-talk],[data-next]')?.focus({preventScroll:true});});
 root.querySelectorAll('[data-help],[data-detail]').forEach(b=>b.onclick=()=>{help=true;render();root.querySelector('[data-help-close]')?.focus();});
 root.querySelector('[data-help-close]')?.addEventListener('click',()=>{help=false;render();root.querySelector('[data-help]')?.focus();});
 root.querySelector('[data-defer]')?.addEventListener('click',()=>{step=7;tab='推荐';render();});
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(step===3&&b.dataset.tab!=='新伙伴')step=7;tab=b.dataset.tab;render();});
 root.querySelectorAll('[data-stock]').forEach(input=>input.onchange=()=>{const v=Number(input.value);stock[Number(input.dataset.stock)]=Number.isFinite(v)?Math.max(0,Math.min(Number(input.max),Math.floor(v))):0;render();});
 root.querySelector('[data-restart]')?.addEventListener('click',restart);
 }
 document.querySelector('#step').value=step;document.querySelector('#progress').textContent=`${step+1} / 8 · ${names[step]}`;
}
function restart(){dialogueTurn=0;step=0;tab='推荐';help=false;stock=[6,6];render();}
document.querySelector('#restart').onclick=restart;
document.querySelector('#step').onchange=e=>{dialogueTurn=0;step=Number(e.target.value);tab=step===3?'新伙伴':'推荐';help=false;render();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&help){help=false;render();}});
render();
const galleryState=Object.fromEntries(Object.keys(VISITORS).map(id=>[id,{repeat:false,help:false,closed:false,turn:0}]));
function renderGallery(){
 const root=document.querySelector('#background-gallery');
 root.innerHTML=Object.entries(VISITORS).map(([id,v])=>{const state=galleryState[id],turns=VISITOR_DIALOGUES[id][state.repeat?'repeat':'first'],current=turns[state.turn],last=state.turn===turns.length-1;return `<article class="background-card" data-visitor="${id}"><header class="scene-review-head"><h3>${v.name}</h3><small>${v.composition}</small></header><div class="scene-preview"><img src="./assets/${v.scene}" class="background-art scene-full" alt="${v.name}在${v.place}" draggable="false"><span class="place-tag">${v.place}</span><button class="scene-help" data-scene-help aria-label="查看常客帮助">?</button>${state.closed?'<button class="scene-reopen primary" data-scene-reopen>再聊两句</button>':`<section class="scene-dialogue dialogue" aria-label="${v.name}对话"><span class="speaker">${v.name}</span>${state.turn?`<p class="player-reply">你：${turns[state.turn-1].reply}</p>`:''}<p class="speech">${current.text}</p>${last?`<p class="dialogue-cue">${state.repeat?v.request:v.cue}</p>`:''}<div class="actions"><button class="defer" data-scene-close>先忙去了</button><button class="primary" ${last?'data-scene-close':'data-scene-next'}>${current.reply}</button></div></section>`}${state.help?`<div class="scene-help-panel" role="region" aria-label="常客帮助"><h4>常客来访</h4><p>客人的话说的是自己的需要。具体品种、数量和库存显示在需求卡上，不用从对白里猜规则。</p><p>暂时离开后，可以再从生意里的常客入口查看。阅读对话不扣伙伴或 CP。</p><button class="primary" data-scene-help-close>返回对话</button></div>`:''}</div><footer class="scene-review-controls"><div role="group" aria-label="${v.name}对白时机"><button data-scene-phase="first" aria-pressed="${!state.repeat}">来访</button><button data-scene-phase="repeat" aria-pressed="${state.repeat}">回访</button></div><a href="./assets/${v.scene}" target="_blank" rel="noopener">完整场景 ↗</a></footer></article>`;}).join('');
 root.querySelectorAll('[data-visitor]').forEach(card=>{const id=card.dataset.visitor,state=galleryState[id];
  card.querySelectorAll('[data-scene-phase]').forEach(b=>b.onclick=()=>{state.repeat=b.dataset.scenePhase==='repeat';state.turn=0;state.closed=false;state.help=false;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-phase="${b.dataset.scenePhase}"]`).focus({preventScroll:true});});
  card.querySelector('[data-scene-next]')?.addEventListener('click',()=>{state.turn++;renderGallery();document.querySelector(`[data-visitor="${id}"] .scene-dialogue .primary`).focus({preventScroll:true});});
  card.querySelectorAll('[data-scene-close]').forEach(b=>b.onclick=()=>{state.closed=true;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-reopen]`).focus({preventScroll:true});});
  card.querySelector('[data-scene-reopen]')?.addEventListener('click',()=>{state.closed=false;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-close]`).focus({preventScroll:true});});
  card.querySelector('[data-scene-help]').onclick=()=>{state.help=true;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-help-close]`).focus({preventScroll:true});};
  card.querySelector('[data-scene-help-close]')?.addEventListener('click',()=>{state.help=false;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-help]`).focus({preventScroll:true});});
 });
}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const id=Object.keys(galleryState).find(id=>galleryState[id].help);if(id){galleryState[id].help=false;renderGallery();document.querySelector(`[data-visitor="${id}"] [data-scene-help]`).focus({preventScroll:true});}}});
renderGallery();
