import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
import * as E from '../../../web/engine.js';
import {syncProgress} from '../../../web/progression.js';
import {openBusiness} from '../../../web/business.js';
import {departRegional} from '../../../web/regional-exploration.js';
import {REGIONAL,resolveSpecies} from '../../../web/content-registry.js';
const {chromium}=await import('file:///'+process.env.APPDATA.replaceAll('\\','/')+'/npm/node_modules/gsd-pi/node_modules/playwright-core/index.mjs');
const dir=new URL('./',import.meta.url),pkg='com.jibao.kitchen.qa241',adbPath='D:/gxy_code/_toolchain/android-sdk/platform-tools/adb.exe';
const adb=(...args)=>execFileSync(adbPath,['-s','AYXGVB6126000685',...args],{env:{...process.env,ADB_LIBUSB:'1'},encoding:'utf8',windowsHide:true});
let b,p;const checks=[],errors=[];let passed=false;
async function connect(){b=await chromium.connectOverCDP('http://127.0.0.1:9223');p=b.contexts()[0].pages()[0];p.on('pageerror',e=>errors.push(e.message));await p.waitForLoadState();}
async function start(){const x=p.getByRole('button',{name:'开始游戏',exact:true});if(await x.count())await x.click();await p.locator('[data-control-id="nav:0"][tabindex="0"]').waitFor();await p.waitForTimeout(550);}
async function read(){return p.evaluate(()=>JSON.parse(JSON.parse(ChickNative.loadSave()).raw));}
async function installState(s){await writeFile(new URL('last-fixture.json',dir),JSON.stringify(s,null,2));const result=await p.evaluate(raw=>{const r=JSON.parse(ChickNative.importGame(raw));if(r.ok)location.reload();return r;},JSON.stringify(s));assert.equal(result.ok,true,JSON.stringify(result));await p.waitForTimeout(500);await start();}
async function snap(name){await p.screenshot({path:new URL(name+'.png',dir).pathname.replace(/^\/([A-Za-z]:)/,'$1')});}
async function restart(){await b.close();adb('shell','am','force-stop',pkg);adb('shell','am','start','-W','-n',pkg+'/com.jibao.kitchen.MainActivity');const pid=adb('shell','pidof',pkg).trim();adb('forward','tcp:9223','localabstract:webview_devtools_remote_'+pid);await new Promise(r=>setTimeout(r,800));await connect();await start();}
try{
 await connect();await writeFile(new URL('initial-qa-save.json',dir),JSON.stringify(await read(),null,2));await start();
 for(const name of ['new-v3','early-v1','early-v3','mid-v3','complete193-v3','rich-stock-v3']){
  const source=JSON.parse(await readFile(new URL('../../../tests/fixtures/golden/'+name+'.json',dir),'utf8'));await installState(source);const s=await read();const expected=JSON.parse(await readFile(new URL('../../../tests/fixtures/golden/expected.json',dir),'utf8')).cases[name];assert.equal(s.version,6);assert.equal(s.cp,expected.assets.cp);assert.deepEqual(s.total,expected.assets.total);assert.deepEqual(s.farm,expected.assets.farm);assert.deepEqual(s.ingredients,expected.assets.ingredients);
  const hidden=REGIONAL.species.filter(c=>!(s.total[c.key]>0)).map(c=>resolveSpecies(c.key).title_zh_CN);
  for(const place of ['农场','生意','寻访','图鉴','厨房']){await p.getByRole('button',{name:place,exact:true}).click();await p.waitForTimeout(150);const html=await p.locator('#game').evaluate(x=>x.innerHTML);for(const n of hidden)assert.ok(!html.includes(n),name+' leaks '+n);}
  await snap('golden-'+name);await p.reload();await start();const again=await read();assert.equal(again.cp,s.cp);assert.deepEqual(again.total,s.total);await writeFile(new URL('golden-'+name+'-after.json',dir),JSON.stringify(again,null,2));checks.push({name:'golden-'+name,passed:true,cp:again.cp,schema:again.version});
 }
 const atomic=await p.evaluate(()=>{const before=JSON.parse(ChickNative.loadSave()).raw,s=JSON.parse(before),results=[];for(const patch of [{version:99},{cp:-1},{version:6,meta:{revision:-1}}]){const r=JSON.parse(ChickNative.importGame(JSON.stringify({...s,...patch})));results.push({accepted:r.ok,unchanged:JSON.parse(ChickNative.loadSave()).raw===before});}return results;});assert.ok(atomic.every(x=>!x.accepted&&x.unchanged));checks.push({name:'native-future-corrupt-rejected-without-overwrite',passed:true,cases:atomic.length});
 const t=Date.now()-25*3600000;let s=E.freshState(t,4040);s.kitchenLevel=1;s.cp=3000;s.toolLevels[1]=0;s.total=Object.fromEntries(Array.from({length:30},(_,i)=>[`0:${i}`,i?3:400]));s.farm={'0:0':30,'0:3':12,'0:1':3};s.progress.orders['first-sale']={accepted:true,choice:'0:0',delivered:12,completed:true};s.progress.tutorialSeen=true;syncProgress(s);s=E.normalizeSave(s,t);openBusiness(s,{menuId:'MN1',stock:{'0:0':6,'0:3':6}},t);departRegional(s,{regionId:'V',placeId:'V:0',focus:'specimen',members:['0:1']},t);s=E.normalizeSave(s,t);const v5=structuredClone(s);v5.version=5;v5.meta.migrationHistory.pop();for(const k of ['collections','regulars','projects','menus'])delete v5.expansion[k];await installState(v5);s=await read();assert.equal(s.version,6);assert.equal(s.expansion.business.lastReport.totalSold,12);assert.ok(s.progress.trip.returnedAt);const cp=s.cp;await p.getByRole('button',{name:'生意',exact:true}).click();await snap('expired-business');await restart();s=await read();assert.equal(s.cp,cp);assert.equal(s.expansion.business.lastReport.totalSold,12);await p.getByRole('button',{name:'寻访',exact:true}).click();await p.locator('[data-regional-claim]').first().click();await p.locator('[data-yes]').click();s=await read();assert.ok(s.expansion.discovery.cards['V-S1']);const cards=structuredClone(s.expansion.discovery.cards),money=s.cp;await restart();s=await read();assert.equal(s.cp,money);assert.deepEqual(s.expansion.discovery.cards,cards);checks.push({name:'schema5-live-business-trip-after-25h-kill-restart-claim-once',passed:true,fixturePastTime:true,systemClockChanged:false});
 await p.getByRole('button',{name:'图鉴',exact:true}).click();await snap('book-physical');const nav=await p.locator('#main-nav button').evaluateAll(xs=>xs.map(x=>({name:x.textContent,w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})));assert.equal(nav.length,5);assert.ok(nav.every(x=>x.w>=44&&x.h>=44));checks.push({name:'physical-safe-area-five-nav-44px',passed:true,nav});
 await writeFile(new URL('after-suite-save.json',dir),JSON.stringify(await read(),null,2));assert.deepEqual(errors,[]);passed=true;
}catch(e){if(p)try{await snap('suite-failure');await writeFile(new URL('suite-failure.txt',dir),await p.locator('body').innerText());}catch{}throw e;}
finally{await b?.close();await writeFile(new URL('suite-report.json',dir),JSON.stringify({checkedAt:new Date().toISOString(),passed,checks,errors,physicalDevice:true,package:pkg,originalAppModified:false},null,2));console.log(JSON.stringify({passed,checks,errors},null,2));}
