import {createRequire} from 'node:module';import {writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import * as E from '../../web/engine.js';import {learnSkill} from '../../web/progression.js';
const {chromium}=createRequire(import.meta.url)(process.env.APPDATA+'/npm/node_modules/gsd-pi/node_modules/playwright-core');const b=await chromium.launch({headless:true});const report={actions:[],errors:[],viewports:[]};
const save=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('chick-kitchen-v1')));const shot=(p,n)=>p.screenshot({path:'artifacts/round2-review/screens/'+n+'.png'});
async function boot(w,h,s){const c=await b.newContext({viewport:{width:w,height:h},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await c.addInitScript(s=>{window.auditOffset=0;const real=Date.now.bind(Date);Date.now=()=>real()+window.auditOffset;if(!localStorage.getItem('chick-kitchen-v1'))localStorage.setItem('chick-kitchen-v1',JSON.stringify(s));},s);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:4185/');await p.getByRole('button',{name:'开始游戏',exact:true}).tap();await p.waitForTimeout(700);return {p,c};}
try{
const s=E.freshState();s.cp=12580;s.kitchenLevel=2;s.toolLevels=[2,2,2,2,2,2,-1,-1,1];s.duck=true;s.progress.tutorialSeen=true;for(let i=0;i<85;i++){s.farm['0:'+i]=30;s.total['0:'+i]=70;}delete s.total['0:51'];delete s.farm['0:51'];s.ingredients={0:30};learnSkill(s,'TRIP-A');learnSkill(s,'TRIP-A');learnSkill(s,'TRIP-B');
let {p,c}=await boot(390,844,s);await p.locator('.workshop-launch').tap();await p.locator('[data-workshop-tab="trip"]').tap();await p.locator('[data-member="0"]').selectOption('0:0');await p.locator('[data-depart]').tap();await p.locator('[data-yes]').tap();await p.evaluate(()=>window.auditOffset=2*3600000+2000);await p.locator('[data-claim-trip]').waitFor();assert.equal((await save(p)).progress.trip.status,'returned');await shot(p,'42-trip-return-full');await p.locator('[data-claim-trip]').tap();await shot(p,'43-trip-full-feedback');await p.locator('[data-yes]').tap();await p.locator('[data-discard-trip]').tap();await p.locator('[data-yes]').tap();assert.equal((await save(p)).progress.trip.status,'settled');report.actions.push('Departure, 2-hour simulated clock advance, automatic return, full-inventory claim and explicit remaining-material discard inspected.');await c.close();
const early=E.freshState();early.progress.tutorialSeen=true;E.startBatch(early,0,Date.now()-3*3600000,()=>.5);for(const e of early.batch.eggs){e.status='ready';e.blackAt=null;e.animationAt=Date.now()-10000;}({p,c}=await boot(390,844,early));let initial=(await save(p)).cp;for(let i=0;i<24;i++)await p.locator('[data-control-id="egg:'+i+'"]').press('Enter');await shot(p,'44-harvest-feedback');let after=await save(p);assert.equal(after.cp,initial+24);assert.equal(after.total['0:0'],24);await p.locator('[data-control-id="nav:1"]').tap();await p.locator('[data-control-id="farm:harvest"]').tap();await p.getByRole('button',{name:'每种留一只',exact:true}).tap();await shot(p,'45-sale-keep-one');await p.getByRole('button',{name:'确认出售',exact:true}).tap();await shot(p,'46-sale-confirm');await p.locator('[data-yes]').tap();after=await save(p);assert.equal(after.farm['0:0'],1);assert.equal(after.cp,initial+24+69);report.actions.push('Collected 24 via actual keyboard controls, earned 24 CP; keep-one sale sold 23 for 69 CP; retained one and discovery.');await c.close();
for(const [w,h]of [[320,568],[430,932],[844,390]]){({p,c}=await boot(w,h,s));await p.locator('.workshop-launch').tap();await shot(p,'47-skills-'+w);await p.locator('[data-workshop-tab="trip"]').tap();await shot(p,'48-trip-'+w);report.viewports.push({w,h,metrics:await p.locator('.workshop-screen,.workshop-body,.workshop-footer').evaluateAll(es=>es.map(e=>({class:e.className,box:{width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height},font:getComputedStyle(e).fontSize,scroll:e.scrollHeight,client:e.clientHeight})))});await c.close();}
}finally{await writeFile('artifacts/round2-review/flow-report.json',JSON.stringify(report,null,2));await b.close();}

