import {createRequire} from 'node:module';import {writeFile,mkdir,readFile,stat} from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.APPDATA+'/npm/node_modules/gsd-pi/node_modules/playwright-core');const browser=await chromium.launch({headless:true});const out='docs/round2-optimization';await mkdir(out+'/mockups',{recursive:true});const errors=[],checks=[];
try{const p=await browser.newPage({viewport:{width:1400,height:1120},deviceScaleFactor:1,reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4186/docs/round2-optimization/mockup.html');await p.evaluate(()=>document.fonts.ready);await p.waitForLoadState('networkidle');
 for(let i=0;i<6;i++){await p.locator('[data-page="'+i+'"]').click();await p.waitForTimeout(100);await p.locator('#phone').screenshot({path:out+'/mockups/page-'+(i+1)+'.png'});assert.equal(await p.locator('#phone').evaluate(e=>e.scrollWidth>e.clientWidth),false);}
 await p.locator('[data-page="0"]').click();await p.locator('[data-plan="C1"]').click();assert.equal(await p.locator('.points strong').innerText(),'2');await p.locator('[data-action="apply"]').click();await p.locator('[data-action="applied"]').click();assert.match(await p.locator('.toast').innerText(),/演示/);checks.push('Skill draft, points, confirmation and explicit demo feedback');
 await p.locator('[data-page="1"]').click();await p.locator('[data-member="0"]').click();await p.locator('[data-partner="1"]').click();assert.match(await p.locator('.reward-box').innerText(),/39.5%/);checks.push('Partner selection changes probabilities');
 await p.locator('[data-page="2"]').click();await p.locator('[data-action="observation"]').click();await p.locator('[data-action="back-cook"]').last().click();assert.match(await p.locator('.sheet-head').innerText(),/准备这一批/);checks.push('Candidate to observation and back');
 await p.locator('[data-page="4"]').click();await p.locator('[data-qty="-1"]').click();assert.equal(await p.locator('output').innerText(),'5');checks.push('Delivery quantity and quote update');
 await p.locator('[data-page="5"]').click();await p.locator('[data-bonus]').uncheck();assert.match(await p.locator('.bill .total').innerText(),/80/);await p.locator('[data-bonus]').check();assert.match(await p.locator('.bill .total').innerText(),/92/);checks.push('Sale reward toggle recalculates 92 / 80 CP');
 await p.locator('[data-page="2"]').click();await p.locator('[data-fresh]').uncheck();assert.match(await p.locator('.stats').innerText(),/0.5/);await p.locator('[data-fresh]').check();assert.match(await p.locator('.stats').innerText(),/2.5/);checks.push('Freshness toggle distinguishes original 30 minutes from protected 150 minutes');
 for(const i of [1,2]){await p.goto('http://127.0.0.1:4186/docs/round2-optimization/mockup.html?board='+i);await p.waitForLoadState('networkidle');await p.locator('.board').screenshot({path:out+'/mockups/board-'+i+'.png'});}
 await p.setViewportSize({width:390,height:950});await p.goto('http://127.0.0.1:4186/docs/round2-optimization/mockup.html');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:out+'/mockups/review-mobile.png',fullPage:true});checks.push('Review artifact opens at mobile width without horizontal document overflow');
 const md=await readFile('docs/game-design.md','utf8');const ids=[...md.matchAll(/^\| ([CHTOR](?:[1-5]|S)) /gm)].map(x=>x[1]);assert.equal(ids.length,30);assert.equal(new Set(ids).size,30);checks.push('Document includes exactly 30 distinct skill IDs');assert.deepEqual(errors,[]);checks.push('No JavaScript page errors');
 console.log(JSON.stringify({checks,errors},null,2));await writeFile(out+'/mockups/verification.json',JSON.stringify({at:new Date().toISOString(),checks,errors},null,2));
}finally{await browser.close();}
