"""Extract display recipes from the unmodified original cooking branches.

No probability sampling and no changes to recipes.js. Conditions come from the
enclosing source branches; post-cooking transformations are documented separately.
"""
from pathlib import Path
import re
import json
from hashlib import sha256

root = Path(__file__).resolve().parents[1]
source = (root / 'web/recipes.js').read_text(encoding='utf-8-sig')
stack, rows = [], []
for line_no, line in enumerate(source.splitlines(), 1):
    if not line.strip():
        continue
    indent = len(line) - len(line.lstrip())
    while stack and stack[-1][0] >= indent:
        stack.pop()
    branch = re.search(r'(?:else )?if \((.+)\) \{$', line.strip())
    if branch:
        stack.append((indent, branch[1]))
    match = re.fullmatch(r'add\((\d+)\);', line.strip())
    if not match:
        continue
    conditions = ' && '.join(condition for _, condition in stack)
    egg = int(re.search(r'_eggID == (\d)', conditions)[1])
    tool = int(re.search(r'_tool1_ID == (\d)', conditions)[1])
    ingredients = sorted(set(map(int, re.findall(r'ingredients\[\d\] \?\? -1\) == (\d+)', conditions))))
    level = max([0] + list(map(int, re.findall(r'tool_1_level\d* >= (\d+)', conditions))))
    kitchen = max([max(0, len(ingredients)-1)] + list(map(int, re.findall(r'tool_0_0_level >= (\d+)', conditions))))
    row = dict(egg=egg, id=int(match[1]), toolId=tool, minLevel=level, minKitchen=kitchen,
               ingredients=ingredients, kind='pool', sourceLine=line_no)
    flag = re.search(r'campaign_char_[01]_\d+', conditions)
    if flag:
        row['campaign'] = flag[0]
    total = re.search(r'totalChars([01])Cnt >= (\d+)', conditions)
    if total:
        row['collectionTotal'] = [int(total[1]), int(total[2])]
    if egg == 0 and row['id'] in (51, 52):
        row['time'] = 'day-phoenix' if row['id'] == 52 else 'other-phoenix'
        row['note'] = '每批有 10% 机会加入对应凤凰的结果池；加入后仍要随机抽取，并非 10% 的最终获得率。'
    elif egg == 1 and row['id'] == 27:
        row['note'] = '每批有 1/8 机会加入结果池，加入后仍要随机抽取。'
    if egg == 0 and row['id'] == 9:
        row['note'] = '在这只鸡宝的破壳时刻附近查看游戏；晚于该时刻 10 秒才处理时，会变为水煮蛋鸡。'
    rows.append(row)

for char_id in range(89, 104):
    rows.append(dict(egg=0,id=char_id,toolId=0,minLevel=0,minKitchen=0,ingredients=[68],kind='sign',
                     note='先到神社抽到对应签礼，再用保温灯调理。已有御神签的结果由所持签礼决定，不能任意改成另一种。'))
for char_id, tool, ingredient in ((106,1,69),(107,2,70)):
    rows.append(dict(egg=0,id=char_id,toolId=tool,minLevel=0,minKitchen=0,ingredients=[ingredient],kind='gift',
                     note='对应神社赠品每批安排一只，保持厨房清洁并及时收取。'))

changes = {
    0: {1:(0,'厨房脏污、没有守护符时，普通鸡宝破壳有机会变为病鸡宝。'),
        2:(0,'保温灯以外的普通料理，成熟后超过各自保鲜时间且没有保鲜剂，有机会烧焦。'),
        34:(1,'厨房 Lv.2 起，脏污厨房的病变分支可能出现。'),
        35:(1,'厨房 Lv.2 起，普通烧焦变化中极少出现。'),
        53:(2,'厨房 Lv.3 起，脏污厨房的病变分支可能出现。'),
        54:(2,'厨房 Lv.3 起，普通烧焦变化中的稀有分支。'),
        68:(3,'厨房 Lv.4，脏污厨房的病变分支可能出现。'),
        70:(0,'烧水壶调理的普通饮品，超过各自保鲜时间且未使用保鲜剂后变化。'),
        110:(0,'面包机调理的普通面包，超过各自保鲜时间且未使用保鲜剂后变化。'),
        104:(0,'先收录普通鸡宝，再完成神社「时空旅行」委托；在委托中使用一只农场里的普通鸡宝进行旅行。')},
    1: {1:(0,'厨房脏污、没有守护符时，普通鸭宝破壳有机会变为病鸭宝。'),
        2:(0,'保温灯以外的普通料理，成熟后超过各自保鲜时间且没有保鲜剂，有机会烧焦。'),
        19:(1,'厨房 Lv.2 起，脏污厨房的病变分支可能出现。'),
        20:(1,'厨房 Lv.2 起，普通烧焦变化中极少出现。'),
        29:(2,'厨房 Lv.3 起，脏污厨房的病变分支可能出现。'),
        28:(2,'厨房 Lv.3 起，普通烧焦变化中的稀有分支。'),
        36:(3,'厨房 Lv.4，脏污厨房的病变分支可能出现。'),
        38:(0,'烧水壶调理的普通饮品，超过各自保鲜时间且未使用保鲜剂后变化。'),
        53:(0,'面包机调理的普通面包，超过各自保鲜时间且未使用保鲜剂后变化。')}
}
for egg, entries in changes.items():
    for char_id, (kitchen, note) in entries.items():
        rows.append(dict(egg=egg,id=char_id,toolId=-1,minLevel=0,minKitchen=kitchen,ingredients=[],kind='change',note=note))
keys = [(r['egg'], r['id']) for r in rows]
assert len(keys) == len(set(keys)), 'duplicate original recipes'
expected = {(egg,i) for egg,total in ((0,114),(1,57)) for i in range(total)}
assert set(keys) == expected, f'missing: {expected-set(keys)}; extra: {set(keys)-expected}'
rows.sort(key=lambda r:(r['egg'],r['id']))
output = '// Generated by tools/build-recipe-catalog.py; original rules stay in recipes.js.\n'
output += 'export const RECIPE_SOURCE_SHA256='+json.dumps(sha256(source.encode()).hexdigest())+';\n'
output += 'export const ORIGINAL_RECIPE_CATALOG='+json.dumps(rows,ensure_ascii=False,separators=(',', ':'))+';\n'
(root / 'web/recipe-catalog-data.js').write_text(output, encoding='utf-8')
print(f'Original recipe coverage: {len(rows)} / 171; {sum(r["kind"] == "pool" for r in rows)} cooking branches.')
