"""Build genuine rounded Chinese game faces. No synthetic bold or system fonts."""
from pathlib import Path
import hashlib,json,sys
from fontTools import subset
from fontTools.ttLib import TTFont
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'artifacts/font-source/resource-rounded'
OUT=ROOT/'web/fonts'
texts=''.join(p.read_text(encoding='utf-8') for p in (ROOT/'web').glob('*.js'))
chars={ord(c) for c in texts if ord(c)>=32 and ord(c)!=0xfeff}|set(range(32,127))|{0x00d7,0x00b7}
weights={'Regular':400,'Medium':500,'Bold':700,'Heavy':900}
report={'source':'https://github.com/CyanoHao/Resource-Han-Rounded/releases/tag/v0.990','license':'OFL-1.1','faces':[],'roles':{'Display':[900,30,36],'Heading':[700,23,29],'Label':[700,18,25],'Body':[400,14,20],'Number':[500,14,20]}}
for name,weight in weights.items():
 source=SRC/('ResourceHanRoundedCN-'+name+'.ttf');font=TTFont(source)
 # Source-code syntax symbols unsupported by upstream aren't UI characters.
 needed={c for c in chars if c in font.getBestCmap()}
 requiredCJK={c for c in chars if 0x3400<=c<=0x9fff}
 missing=requiredCJK-set(font.getBestCmap());assert not missing,sorted(missing)
 target=OUT/('journey-rounded-'+name.lower()+'.woff2')
 if '--check' not in sys.argv:
  opts=subset.Options();opts.name_IDs=['*'];opts.name_legacy=True;opts.name_languages=['*'];opts.layout_features=['*'];opts.recalc_timestamp=False
  sub=subset.Subsetter(options=opts);sub.populate(unicodes=needed);sub.subset(font);font.flavor='woff2';font.save(target)
 packed=TTFont(target);assert not(requiredCJK-set(packed.getBestCmap()))
 assert packed['OS/2'].usWeightClass==weight
 report['faces'].append({'name':name,'weight':weight,'CJK':len(requiredCJK),'missingCJK':0,'bytes':target.stat().st_size,'sourceSHA256':hashlib.sha256(source.read_bytes()).hexdigest(),'outputSHA256':hashlib.sha256(target.read_bytes()).hexdigest()})
if '--check' not in sys.argv:
 css='/* Resource Han Rounded CN, SIL OFL 1.1. Generated by build-journey-font.py. */\n'
 for name,weight in weights.items():css+=f"@font-face{{font-family:'Journey Rounded';src:url('./journey-rounded-{name.lower()}.woff2') format('woff2');font-style:normal;font-weight:{weight};font-display:swap}}\n"
 (OUT/'journey-font.css').write_text(css,encoding='utf-8')
(ROOT/'artifacts/journey-precision/font-coverage.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(report,ensure_ascii=False))
