"""Read original character alpha bounds and write UI-only crop metadata.

Original PNGs are opened read-only. The game renderer and sprite manifest are
not changed. Run with --check to validate both source bounds and saved metadata
without writing any files.
"""

import argparse
import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "web" / "portrait-frames.js"
COUNTS = (114, 57)
PADDING = 2


def read_frames():
    frames = []
    for egg, expected_count in enumerate(COUNTS):
        group = []
        for species_id in range(expected_count):
            path = ROOT / f"assets/png/Character/character_{egg}/character_{egg}_{species_id}_0_0.png"
            with Image.open(path) as source:
                if source.size != (120, 120) or source.mode != "RGBA":
                    raise ValueError(f"Unexpected original image format: {path}")
                bounds = source.getchannel("A").getbbox()
                if bounds is None:
                    raise ValueError(f"No visible pixels: {path}")
                left, top, right, bottom = bounds
                x, y = max(0, left - PADDING), max(0, top - PADDING)
                end_x, end_y = min(120, right + PADDING), min(120, bottom + PADDING)
                frame = [x, y, end_x - x, end_y - y]
                if not (0 <= x < end_x <= 120 and 0 <= y < end_y <= 120):
                    raise ValueError(f"Invalid frame {frame}: {path}")
                if not (x <= left and y <= top and end_x >= right and end_y >= bottom):
                    raise ValueError(f"Frame cuts visible pixels: {path}")
                group.append(frame)
        frames.append(group)
    return frames


def module_source(frames):
    groups = []
    for egg, group in enumerate(frames):
        entries = [f"    {json.dumps(frame, separators=(',', ':'))}, // {egg}:{species_id}"
                   for species_id, frame in enumerate(group)]
        groups.append("  [\n" + "\n".join(entries) + "\n  ]")
    return """// Generated by tools/build-portrait-frames.py from read-only PNG alpha bounds.
// UI portrait crops only: keep gameplay sprite positions and assets unchanged.
// Bounds preserve every nonzero alpha pixel plus up to 2 px of padding.
const FRAMES = [
""" + ",\n".join(groups) + """
];

export function originalPortraitFrame(egg,id){
  if(!Number.isInteger(egg)||!Number.isInteger(id))return undefined;
  const frame=FRAMES[egg]?.[id];
  if(!frame)return undefined;
  return {file:`/assets/png/Character/character_${egg}/character_${egg}_${id}_0_0.png`,frame:[...frame],size:[120,120]};
}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate sources and existing metadata without writes")
    args = parser.parse_args()
    frames = read_frames()
    source = module_source(frames)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != source:
            raise SystemExit("Portrait metadata is missing or differs from current source alpha bounds.")
        print(f"Read-only check passed: {sum(map(len, frames))} frames within 120x120, all alpha pixels retained, metadata matches.")
    else:
        OUTPUT.write_text(source, encoding="utf-8", newline="\n")
        print(f"Wrote {OUTPUT.relative_to(ROOT)}: {sum(map(len, frames))} UI portrait frames; source images unchanged.")


if __name__ == "__main__":
    main()
