import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import * as E from '../web/engine.js';
import * as P from '../web/progression.js';
import * as T from '../web/exploration.js';
import {setStoryAmount} from './qa-business-stock.mjs';
const {chromium}=createRequire(import.meta.url)(process.argv[2]??process.env.APPDATA+'/npm/node_modules/gsd-pi/node_modules/playwright-core');
const base=process.argv[3]??'http://127.0.0.1:4197',out=resolve(process.argv[5]??'artifacts/round2-implementation/screens');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.argv[4]?{executablePath:process.argv[4]}:{})}),errors=[],checks=[],shots=[];
const read=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('chick-kitchen-v1')));
function mature(){const s=E.freshState();s.cp=12580;s.kitchenLevel=3;s.toolLevels.fill(2);s.duck=true;s.progress.tutorialSeen=true;for(let i=0;i<89;i++){s.farm['0:'+i]=30;s.total['0:'+i]=100;}for(const i of [4,51,52]){delete s.total['0:'+i];delete s.farm['0:'+i];}s.ingredients={0:4,1:3,8:2,13:2,16:2};return s;}
async function boot(w,h,s=mature()){
 const c=await browser.newContext({viewport:{width:w,height:h},isMobile:w<500,hasTouch:w<500,reducedMotion:'reduce'});
 await c.addInitScript(s=>{window.__qaOffset=0;const real=Date.now.bind(Date);Date.now=()=>real()+window.__qaOffset;if(!localStorage.getItem('chick-kitchen-v1'))localStorage.setItem('chick-kitchen-v1',JSON.stringify(s));},s);
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/');await p.getByRole('button',{name:'开始游戏',exact:true}).click();await p.locator('.workshop-launch').waitFor();await p.waitForTimeout(650);return {c,p};
}
async function shot(p,name){await p.screenshot({path:resolve(out,name+'.png')});shots.push(name);}
async function fits(p,sel){const a=await p.locator(sel).evaluate(el=>{const r=el.getBoundingClientRect(),g=document.querySelector('#game').getBoundingClientRect();const body=el.querySelector(':scope>.gd-body')??el;/* kit popups: the title board and close button overhang on purpose */return {inside:r.left>=g.left-1&&r.right<=g.right+1&&r.top>=g.top-1&&r.bottom<=g.bottom+1,overflow:body.scrollWidth-body.clientWidth};});assert.ok(a.inside,sel+' inside game');assert.ok(a.overflow<=1,sel+' no horizontal overflow');}
let active;
try{
 for(const [w,h]of [[320,568],[375,667],[390,844],[430,932],[844,390]]){
  const {c,p}=await boot(w,h);active=p;await p.locator('.workshop-launch').click();await fits(p,'.workshop-screen');await shot(p,'skills-'+w);
  const before=await read(p);await p.locator('[data-learn="CUL-1"]').click();assert.deepEqual((await read(p)).progress.skills,before.progress.skills);await shot(p,'draft-'+w);await p.locator('[data-plan-cancel]').click();await p.locator('[data-learn="CUL-1"]').click();await p.locator('[data-plan-apply]').click();await p.locator('[data-yes]').click();assert.equal((await read(p)).progress.skills['CUL-1'],1);await shot(p,'learned-'+w);
  await p.locator('#main-nav').getByRole('button',{name:'生意',exact:true}).click();await p.locator('#panels .bh-order:has(.bh-tag.is-story) [data-order-detail]').click();await p.locator('#panels [data-order-story]').click();await shot(p,'order-'+w);await p.locator('[data-accept="first-sale"]').click();await setStoryAmount(p,'first-sale',12);await p.locator('[data-deliver="first-sale"]').click();await shot(p,'order-confirm-'+w);await p.locator('[data-yes]').click();assert.equal((await read(p)).progress.orders['first-sale'].completed,true);await p.locator('[data-story-back]').click();
  // 2026-10-07: trips start from the region map (谷地 runs the old 菜园 route); 地点与方向 compares a three-member team
  await p.locator('#main-nav').getByRole('button',{name:'寻访',exact:true}).click();await p.locator('#panels [data-regional-region="V"]').click();await p.locator('#panels [data-journey-enter]').click();
  for(const [i,k]of [[0,'0:0'],[1,'0:3'],[2,'0:8']]){await p.locator('[data-regional-slot="'+i+'"]').click();if(i===2)await shot(p,'picker-'+w);await p.locator('[data-regional-member="'+k+'"]').click();}
  await fits(p,'.regional-screen');/* textContent: short screens hide the guaranteed-materials line */assert.match(await p.locator('.journey-preview').textContent(),/34% 机会再多 1 份/);assert.match(await p.locator('.journey-preview').textContent(),/32% 机会带回 1 条伙伴线索|这里暂时没有伙伴线索/);await shot(p,'trip-'+w);await p.locator('[data-regional-depart]').click();await p.locator('[data-journey-confirm]').click();await shot(p,'running-'+w);const trip=(await read(p)).progress.trip;assert.equal(trip.status,'running');
  await p.reload();await p.getByRole('button',{name:'开始游戏',exact:true}).click();await p.waitForTimeout(650);await p.locator('#main-nav').getByRole('button',{name:'寻访',exact:true}).click();await p.evaluate(()=>window.__qaOffset+=2*3600000+1500);await p.locator('[data-regional-claim]').waitFor();await shot(p,'returned-'+w);await p.locator('[data-regional-claim]').click();await p.waitForTimeout(300);if(await p.locator('#dialog-layer [data-yes]').count())await p.locator('#dialog-layer [data-yes]').click();assert.equal((await read(p)).progress.trip.status,'settled');
  await p.locator('#main-nav').getByRole('button',{name:'厨房',exact:true}).click();await p.locator('[data-control-id="tool:0"]').click();await fits(p,'.cooking-dialog');await shot(p,'cook-'+w);await p.locator('[data-preview-species="0:51"],[data-preview-species="0:52"]').first().click();assert.equal(await p.locator('[data-workshop-tab]').count(),0);assert.ok(!(await p.locator('.workshop-screen').innerText()).includes('火凤凰'));await shot(p,'observation-'+w);await p.locator('[data-observe-back]').click();assert.equal(await p.locator('.cooking-dialog .candidate-list').count(),1);await p.locator('[data-no]').click();
  // Real kitchen loop, accelerated only in this isolated browser context.
  await p.locator('[data-control-id="tool:0"]').click();await p.locator('[data-yes]').click();assert.equal((await read(p)).batch.eggs.length,24);await p.evaluate(()=>window.__qaOffset+=3*3600000);await p.waitForTimeout(3500);await p.locator('[data-control-id^="egg:"]').first().press('Enter');assert.ok((await read(p)).batch.eggs.some(e=>e.collected));
  await c.close();checks.push(w+'×'+h+': draft/apply, order, 3-member comparison, reload/return/claim, independent observation/back, cook');
 }
 // State coverage beyond the main flow.
 {const {c,p}=await boot(390,844,E.freshState());active=p;await p.locator('.workshop-launch').click();await shot(p,'new-locked');if(await p.locator('.future-skills').count()&&await p.locator('.future-skills').getAttribute('open')===null)await p.locator('.future-skills>summary').click();await p.locator('[data-skill-detail="CUL-1"]').click();await shot(p,'locked-detail');await c.close();}
 {const s=mature();s.cp=20;for(const id of ['OBS-1','OBS-4'])P.learnSkill(s,id);const {c,p}=await boot(390,844,s);active=p;await p.locator('[data-control-id="tool:0"]').click();await p.locator('[data-preview-species="0:51"],[data-preview-species="0:52"]').first().click();await p.locator('[data-study]').click();await p.locator('[data-yes]').click();await shot(p,'insufficient-cp');assert.match(await p.locator('.confirm').innerText(),/CP还差80/);await c.close();}
 {const s=mature();s.ingredients={0:30};P.learnSkill(s,'TRIP-1');T.depart(s,{routeId:'yard',members:['0:0','0:3','0:8']},Date.now()-3*3600000,()=>0);const {c,p}=await boot(390,844,s);active=p;await p.locator('#main-nav').getByRole('button',{name:'寻访',exact:true}).click();await p.locator('#panels [data-regional-claim]').waitFor();await shot(p,'full-bag');const before=(await read(p)).cp;await p.locator('#panels .regional-basket details summary').click();await p.locator('[data-regional-claim-notes]').click();await p.locator('#dialog-layer [data-yes]').click();assert.equal((await read(p)).cp,before+6);await p.locator('#panels .regional-basket details summary').click();await p.locator('[data-regional-claim-notes]').click();await p.waitForTimeout(300);if(await p.locator('#dialog-layer [data-yes]').count())await p.locator('#dialog-layer [data-yes]').click();assert.equal((await read(p)).cp,before+6);await c.close();}
 {const {c,p}=await boot(1280,900);active=p;await p.locator('.workshop-launch').click();await p.locator('[data-skill-detail="CUL-1"]').hover();await shot(p,'hover');await p.locator('[data-skill-detail="CUL-1"]').focus();await shot(p,'focus');await p.locator('[data-skill-detail="CUL-1"]').press('Enter');await p.locator('[data-detail-learn]').press('Enter');assert.match(await p.locator('.draft-status').innerText(),/尚未生效/);await shot(p,'keyboard-selected');await c.close();}
 {const s=mature();P.learnSkill(s,'CUL-1');E.startBatch(s,0,Date.now()-3*3600000,()=>0);const {c,p}=await boot(390,844,s);active=p;await p.waitForTimeout(3500);await p.locator('[data-control-id^="egg:"]').first().press('Enter');await shot(p,'effect-trigger');assert.match(await p.locator('.game-toast').innerText(),/额外/);await c.close();}
 {const {c,p}=await boot(390,844);active=p;await p.locator('.workshop-launch').click();await p.locator('[data-learn="CUL-1"]').click();const saved=await read(p);await p.evaluate(()=>{const original=Storage.prototype.setItem;window.__qaRestore=()=>Storage.prototype.setItem=original;Storage.prototype.setItem=function(){throw new DOMException('QA full disk','QuotaExceededError');};});await p.locator('[data-plan-apply]').click();await shot(p,'save-failure');assert.deepEqual((await read(p)).progress.skills,saved.progress.skills);await p.evaluate(()=>window.__qaRestore());await c.close();}
 assert.deepEqual(errors,[]);console.log('Round2 UI passed: '+checks.length+' viewport flows; '+shots.length+' screenshots');
}catch(e){if(active&&!active.isClosed()){console.log(await active.locator('body').innerText());await shot(active,'failure');}throw e;}finally{await writeFile(resolve(out,'report.json'),JSON.stringify({at:new Date().toISOString(),checks,shots,errors,nativeDeviceTest:false},null,2));await browser.close();}
