"""User-authorized semantic Asset Sheet segmentation; no new art is drawn here.

Grid windows identify semantics only. Connected alpha components define actual
extraction masks, with tiny stray components removed and antialiased edges kept.
Bounds, optical ground anchors and padding are recorded, never guessed at runtime.
"""
from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
from scipy import ndimage
import numpy as np,json,hashlib
ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'docs/journey-visual-20260925/asset-sheets'
OUT=ROOT/'web/art/golden-journey'
SHEETS={
 'J01-landmarks.png':(3,2,['node-V','node-R','node-T','node-B','place-V-0','place-V-1']),
 'J02-places.png':(3,2,['place-R-0','place-R-1','place-T-0','place-T-1','place-B-0','place-B-1']),
 'J03-travel.png':(4,4,['flag','backpack','mat','button','pouch','magnifier','note','envelope','lock','footprints','ribbon','unknown','map-icon','environment-yard','environment-water','environment-wood']),
 'J04-materials.png':(4,2,[f'material-{i}' for i in range(75,83)])}
manifest={'version':1,'workflow':'Mockup > semantic sheet > connected alpha segmentation > cleanup > bounds normalization > runtime','assets':[]}
for file,(cols,rows,names) in SHEETS.items():
 if not (SOURCE/file).exists():continue
 im=Image.open(SOURCE/file).convert('RGBA');w,h=im.size
 full=np.array(im);source_alpha=full[:,:,3]
 all_labels,num=ndimage.label(source_alpha>=16)
 all_sizes=np.bincount(all_labels.ravel());all_sizes[0]=0
 centers=ndimage.center_of_mass(source_alpha,all_labels,list(range(1,num+1)))
 groups={i:[] for i in range(cols*rows)}
 for label,(cy,cx) in enumerate(centers,1):
  if all_sizes[label]>=18:groups[min(rows-1,int(cy*rows/h))*cols+min(cols-1,int(cx*cols/w))].append(label)
 for index,name in enumerate(names):
  x=index%cols;y=index//cols;cell=(round(x*w/cols),round(y*h/rows),round((x+1)*w/cols),round((y+1)*h/rows))
  arr=full.copy();alpha=source_alpha
  candidates=groups[index];assert candidates,f'Empty asset: {name}'
  # Retain meaningful disconnected elements (e.g. water droplets, two footprints).
  kept=[label for label in candidates if all_sizes[label]>=max(18,max(all_sizes[candidates])*.0025)]
  core=np.isin(all_labels,kept)
  mask=ndimage.binary_dilation(core,iterations=2)&(alpha>=8)
  arr[:,:,3]=np.where(mask,alpha,0)
  piece=Image.fromarray(arr);bounds=piece.getchannel('A').getbbox()
  assert bounds and bounds[0]>0 and bounds[1]>0 and bounds[2]<w and bounds[3]<h,f'Sheet boundary touches art: {name} {bounds}'
  cropped=piece.crop(bounds);pad=8
  result=Image.new('RGBA',(cropped.width+pad*2,cropped.height+pad*2));result.paste(cropped,(pad,pad))
  target=OUT/f'{name}.png';result.save(target)
  ground=name.startswith(('node-','place-')) or name in ['flag','mat','backpack']
  entry={'id':name,'path':f'/web/art/golden-journey/{name}.png','source':str((SOURCE/file).relative_to(ROOT)).replace('\\','/'),'sourceCell':cell,'sourceBounds':bounds,'size':result.size,'visualBounds':[pad,pad,cropped.width,cropped.height],'padding':[pad]*4,'anchor':[pad+cropped.width/2,pad+cropped.height*(.94 if ground else .5)],'anchorKind':'ground-center' if ground else 'center','runtimeVisualHeight':125 if ground else 48,'components':len(kept),'removedStrayPixels':int(sum(all_sizes[candidates])-np.count_nonzero(core)),'transparent':True,'sha256':hashlib.sha256(target.read_bytes()).hexdigest()}
  manifest['assets'].append(entry);print(name,result.size,len(kept))
terrain=OUT/'world-terrain.png'
if terrain.exists():
 im=Image.open(terrain);manifest['assets'].append({'id':'world-terrain','path':'/web/art/golden-journey/world-terrain.png','source':'docs/journey-visual-20260925/asset-sheets/J05-terrain.png','size':im.size,'visualBounds':[0,0,*im.size],'padding':[0]*4,'anchor':[im.width/2,im.height/2],'anchorKind':'center','transparent':False,'contains':'only static geography, no nodes, characters, text, routes, states or controls','sha256':hashlib.sha256(terrain.read_bytes()).hexdigest()})
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Emit a read-only layout index for runtime: the pixels always come from PNGs.
metrics={e['id']:{k:e[k] for k in ['size','visualBounds','anchor','anchorKind']} for e in manifest['assets']}
(ROOT/'web/journey-art-metrics.js').write_text('// Generated by segment-journey-assets.py; presentation geometry only.\nexport const JOURNEY_METRICS='+json.dumps(metrics,separators=(',',':'))+';\n',encoding='utf-8')
items=[e for e in manifest['assets'] if e['id']!='world-terrain'];board=Image.new('RGB',(1000,((len(items)+4)//5)*170),'#fff9e4');draw=ImageDraw.Draw(board)
for i,e in enumerate(items):
 im=Image.open(OUT/(e['id']+'.png'));im.thumbnail((180,135));x=(i%5)*200+(200-im.width)//2;y=(i//5)*170
 board.paste(im,(x,y),im);draw.text(((i%5)*200+10,y+140),e['id'],fill='#5d4026')
board.save(ROOT/'artifacts/journey-family/segmented-assets.png')
