"""Semantic component segmentation, cleanup and normalization of J06-J08.

Never rasterizes text or UI screens. Alpha components, not rectangular cells,
define the cutouts. Original generated sheets are retained for provenance.
"""
from pathlib import Path
import base64
import hashlib,json
import numpy as np
from PIL import Image,ImageDraw
from scipy import ndimage

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'docs/journey-visual-20260925/asset-sheets'
OUT=ROOT/'web/art/golden-journey'
SHEETS={
 'J12-timer.png':(1,2,['timer-capsule','timer-clock']),
 'J06-precision-ui.png':(4,4,['ribbon','botanical-left','botanical-right','sparkles','brush','reward-slot','nameplate','button','envelope-back','envelope-front','celebration','record-note','tree-round','tree-tall','grass-rock','clock']),
 'J07-precision-landscape.png':(3,3,['node-V','node-T','node-R','node-B','place-V-0','place-V-1','hill','ground','grass-stones']),
 'J10-ui-extracted.png':(2,2,['exact-ribbon','exact-button','exact-nameplate','exact-brush']),
 'J11-reference-environment.png':(5,1,['ref-map-hills','ref-map-ground','ref-map-river','ref-place-environment','ref-hero-ground']),
 'J08-river.png':(1,1,['river']),
 'J09-reference-components.png':(5,5,['ref-'+n for n in ['node-V','node-T','node-R','node-B','place-V-0','place-V-1','tree-round','tree-tall','grass-rock','botanical-left','botanical-right','celebrate-left','celebrate-right','rock','tree-left','character-0-0','character-0-3','character-1-0','sparkle','record-note','action-note','action-magnifier','action-pouch','map-icon']])
}
manifest=json.loads((OUT/'manifest.json').read_text(encoding='utf-8'))
manifest['precisionWorkflow']='Reference > J06/J07/J08 sheets > alpha connected components > remove low-alpha generation halo and stray components > optical bounds > 8px padding > manifest > Runtime'
entries=[]
for file,(cols,rows,names) in SHEETS.items():
 im=Image.open(SOURCE/file).convert('RGBA');arr=np.array(im);a=arr[:,:,3];w,h=im.size
 labels,num=ndimage.label(a>=128);sizes=np.bincount(labels.ravel());sizes[0]=0
 groups={i:[] for i in range(cols*rows)}
 for i,sl in enumerate(ndimage.find_objects(labels),1):
  if sl is None or sizes[i]<25:continue
  yy,xx=ndimage.center_of_mass(a,labels,i)
  cell=min(rows-1,int(yy*rows/h))*cols+min(cols-1,int(xx*cols/w))
  groups[cell].append(i)
 for n,name in enumerate(names):
  ids=groups[n];assert ids,(file,name)
  keep=[i for i in ids if sizes[i]>=max(25,max(sizes[ids])*(.008 if name.startswith('ref-') else .001))]
  if 'character-' in name:keep=[max(ids,key=lambda i:sizes[i])]
  mask=ndimage.binary_dilation(np.isin(labels,keep),iterations=2)&(a>=16)
  piece=arr.copy();piece[:,:,3]=np.where(mask,a,0)
  img=Image.fromarray(piece);bounds=img.getchannel('A').getbbox();crop=img.crop(bounds);pad=8
  asset=Image.new('RGBA',(crop.width+16,crop.height+16));asset.paste(crop,(pad,pad))
  key='precision-'+name;path=OUT/(key+'.png');asset.save(path)
  entry={'id':key,'path':'/web/art/golden-journey/'+path.name,'source':str((SOURCE/file).relative_to(ROOT)).replace('\\','/'),'sourceCell':[n%cols,n//cols,cols,rows], 'sourceBounds':bounds,'size':asset.size,'visualBounds':[pad,pad,crop.width,crop.height],'anchor':[asset.width/2,asset.height/2],'anchorKind':'center','padding':[pad]*4,'alphaCoreThreshold':128,'alphaEdgeThreshold':16,'components':len(keep),'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'transparent':True}
  entries.append(entry)
manifest['assets']=[e for e in manifest['assets'] if not e['id'].startswith('precision-')]+entries
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
metrics={e['id']:{k:e[k] for k in ['size','visualBounds','anchor','anchorKind']} for e in manifest['assets']}
(ROOT/'web/journey-art-metrics.js').write_text('// Generated by segment-journey-assets.py and segment-journey-precision.py.\nexport const JOURNEY_METRICS='+json.dumps(metrics,separators=(',',':'))+';\n',encoding='utf-8')
board=Image.new('RGB',(1200,((len(entries)+4)//5)*200),'#fff9e4');d=ImageDraw.Draw(board)
for i,e in enumerate(entries):
 im=Image.open(OUT/(e['id']+'.png'));im.thumbnail((220,165));x=(i%5)*240+(240-im.width)//2;y=(i//5)*200
 board.paste(im,(x,y),im);d.text(((i%5)*240+8,y+176),e['id'],fill='#5d4026')
board.save(ROOT/'artifacts/journey-precision/segmented-assets.png')
print(json.dumps({'assets':len(entries),'empty':0,'manifest':str(OUT/'manifest.json')}))

# Runtime background wrappers use normalized visual bounds; embedded original PNG
# is required because browsers block external subresources of CSS SVG images.
manifest['wrappers']=[]
for name in ['exact-button','exact-nameplate','exact-ribbon','exact-brush','timer-capsule']:
 e=next(x for x in entries if x['id']=='precision-'+name)
 x,y,w,h=e['visualBounds'];iw,ih=e['size'];data=base64.b64encode((OUT/(e['id']+'.png')).read_bytes()).decode()
 frame=OUT/(e['id']+'-frame.svg')
 frame.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x} {y} {w} {h}" preserveAspectRatio="none"><image href="data:image/png;base64,{data}" width="{iw}" height="{ih}"/></svg>')
 manifest['wrappers'].append({'path':'/web/art/golden-journey/'+frame.name,'asset':e['id'],'viewBox':[x,y,w,h],'embeddedRaster':True,'sha256':hashlib.sha256(frame.read_bytes()).hexdigest()})
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
